version: '3.7'

services:

  eurekaserver:
    image: in28min/mmv3-eurekaserver:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: