version: '3.7'

services:

  currency-exchange:
    image: in28min/mmv3-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://host.docker.internal:3306/vwcurrency
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eurekaserver:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://host.docker.internal:9411/api/v2/spans


networks:
  currency-network: