version: '3.7'

services:
  api-gateway:
    image: in28min/mmv3-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://host.docker.internal:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://host.docker.internal:9411/api/v2/spans

networks:
  currency-network: